services:
  api:
    build:
      context: .
      dockerfile: CodeFest.Api/Dockerfile
    ports:
      - "5050:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=codefest;Username=postgres;Password=${POSTGRES_PASSWORD}
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - codefest-net

  postgres:
    image: exadel/compreface-postgres-db:1.2.0
    environment:
      POSTGRES_DB: codefest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d codefest"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - codefest-net

volumes:
  pg-data:

networks:
  codefest-net:
    driver: bridge
